### ISSUE TITLE
Check state of Yeelight bulb

### ISSUE THREAD

**Issue by Shuggle** [itskenny0/Yeelight-PHP#1]
Hey ! Can we check the state of the Yeelight bulb with your API ?

**Comment by helloiamgergo** [comment]
That's possible.

```
<?php
require "Yeelight.class.php";

$yee = new Yeelight("ip-of-your-bulb", 55443);
$yee->get_prop("power");
$res = $yee->commit();
$yee->disconnect();

var_dump($res);

?>
```

**Comment by Shuggle** [comment]
That's works like a charm. Thanks.

**Comment by helloiamgergo** [comment]
You're welcome. The specification contains lots of useful information: https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf

**Comment by itskenny0** [comment]
Thank you for beating me to it @iambgweb :)
The class should be able to cover all functions described in the spec. 
If not, please let me know.
